export interface ServiceData {
  slug: string;
  name: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  image: string;
  heroHeadline: string;
  heroSub: string;
  intro: string;
  signs: string[];
  treatment: string[];
  prevention: string[];
  faqs: { question: string; answer: string }[];
  schemaType: string;
  serviceType: string;
  areaServed: string;
}

export const pestServices: ServiceData[] = [
  {
    slug: 'spider-control',
    name: 'Spider Control',
    title: 'Spider Control Sydney',
    metaTitle: 'Spider Control Sydney | Safe Spider Removal & Treatment',
    metaDescription: 'Professional spider control across Sydney. Pest-Aside removes webs, nests and the conditions that attract spiders. Family-safe treatments with lasting results.',
    image: '/images/spider.jpg',
    heroHeadline: 'Spider control',
    heroSub: 'Webs gone, worries gone.',
    intro: 'Spiders are a fact of life in Sydney, but that does not mean they need to share your home. Most are harmless, yet a few species found in NSW can deliver painful or medically significant bites. Pest-Aside identifies what is actually present, clears webs and nests, and treats the areas spiders use to travel, shelter and breed. The result is a calmer home and far fewer unwanted encounters.',
    signs: [
      'Webs appearing in corners, eaves, windows and garden areas',
      'Spider egg sacs in quiet, undisturbed spots',
      'Live spiders seen indoors, especially in warm months',
      'Shed skins in basements, garages or storage areas',
    ],
    treatment: [
      'Targeted treatment of webbing sites, entry points and harbourages',
      'Removal of webs and egg sacs from accessible areas',
      'Crack and crevice treatment where spiders shelter',
      'Advice on lighting and garden conditions that attract prey',
    ],
    prevention: [
      'Seal gaps around windows, doors and vents',
      'Reduce exterior lighting that attracts the insects spiders feed on',
      'Keep vegetation trimmed away from walls',
      'Clear stored clutter in garages and sheds',
    ],
    faqs: [
      { question: 'Are the treatments safe for my family and pets?', answer: 'Yes. We use products designed for use in occupied homes and apply them precisely where spiders travel and shelter, not broadcast across living areas.' },
      { question: 'How long does spider control last?', answer: 'Most treatments provide several months of protection. We recommend an annual or seasonal treatment for homes in bushy or waterfront areas.' },
      { question: 'Do you handle venomous spiders?', answer: 'Yes. We can identify and treat for species of concern. If you suspect a Sydney funnel-web or redback, keep your distance and call us promptly.' },
    ],
    schemaType: 'Service',
    serviceType: 'Spider control and removal',
    areaServed: 'Sydney metropolitan area',
  },
  {
    slug: 'cockroach-control',
    name: 'Cockroach Control',
    title: 'Cockroach Control Sydney',
    metaTitle: 'Cockroach Control Sydney | Effective Cockroach Treatment',
    metaDescription: 'Get rid of cockroaches for good. Pest-Aside Sydney targets all cockroach species with tailored gel bait and treatment plans. Long-lasting, family-safe results.',
    image: '/images/cockroach.jpg',
    heroHeadline: 'Cockroach control',
    heroSub: 'Clear them out, keep them out.',
    intro: 'Cockroaches are one of the most resilient pests in Sydney. They spread bacteria, trigger asthma and allergies, and multiply quickly once established. Pest-Aside uses a combination of targeted gel bait, crack and crevice treatment, and harbourage control to break the breeding cycle. We do not just kill what you can see, we address the colony at its source.',
    signs: [
      'Droppings that look like coffee grounds or dark specks',
      'Musty odour in kitchens, pantries or under sinks',
      'Egg cases (oothecae) in dark corners or behind appliances',
      'Live cockroaches seen at night, especially in kitchens and bathrooms',
    ],
    treatment: [
      'Professional gel bait application in key harbourage areas',
      'Crack and crevice treatment behind and under appliances',
      'Insect growth regulator to break the breeding cycle',
      'Targeted treatment of drains, voids and entry points',
    ],
    prevention: [
      'Fix leaking taps and reduce standing water',
      'Store food in sealed containers and clean up crumbs nightly',
      'Seal gaps around pipes, skirtings and behind cabinets',
      'Take out rubbish regularly and keep bins sealed',
    ],
    faqs: [
      { question: 'Why do I still see cockroaches after treatment?', answer: 'It is normal to see reduced activity for a week or two as the bait works through the colony. If you still see live roaches after two weeks, contact us for a follow-up.' },
      { question: 'Do I need to leave my home during treatment?', answer: 'Usually not. Gel bait and crack-and-crevice treatments are applied in inaccessible areas and do not require you to vacate the property.' },
      { question: 'What species do you treat?', answer: 'We treat all common Sydney species including German, American and Australian cockroaches, with different approaches depending on the species.' },
    ],
    schemaType: 'Service',
    serviceType: 'Cockroach extermination and control',
    areaServed: 'Sydney metropolitan area',
  },
  {
    slug: 'german-cockroach-control',
    name: 'German Cockroach Control',
    title: 'German Cockroach Control Sydney',
    metaTitle: 'German Cockroach Control Sydney | Targeted German Roach Treatment',
    metaDescription: 'German cockroaches are the hardest roach to eliminate. Pest-Aside Sydney uses professional gel bait and growth regulators to break the breeding cycle for good.',
    image: '/images/german-cockroach.jpg',
    heroHeadline: 'German cockroach control',
    heroSub: 'The toughest roach, met head on.',
    intro: 'German cockroaches are the most persistent and difficult cockroach species to eliminate. A single female and her offspring can produce thousands of descendants in a year. They hide in tiny cracks near food and water, breed indoors year-round, and quickly develop resistance to over-the-counter sprays. Pest-Aside uses professional-grade gel baits and insect growth regulators that target the colony at every life stage, breaking the breeding cycle rather than just knocking down what you can see.',
    signs: [
      'Small light-brown cockroaches, 10 to 15mm, with two dark stripes behind the head',
      'Droppings like dark specks or coffee grounds in cupboards and drawers',
      'Egg cases glued in cracks, hinges or under appliances',
      'A persistent musty smell in kitchens or bathrooms',
    ],
    treatment: [
      'Professional gel bait applied to cracks, hinges and harbourages',
      'Insect growth regulator to stop nymphs maturing and eggs hatching',
      'Targeted treatment behind appliances, inside voids and around plumbing',
      'Follow-up assessment to confirm colony elimination',
    ],
    prevention: [
      'Eliminate water sources: fix drips, dry sinks overnight',
      'Keep kitchens crumb-free and store all food in sealed containers',
      'Do not leave pet food out overnight',
      'Inspect incoming groceries, cardboard and second-hand appliances',
    ],
    faqs: [
      { question: 'Why are German cockroaches so hard to get rid of?', answer: 'They breed extremely fast, hide in tiny cracks, and are resistant to most consumer sprays. Professional gel bait and growth regulators are the only reliable way to eliminate a colony.' },
      { question: 'How many treatments will I need?', answer: 'A single thorough treatment is often enough, but heavy infestations may need a follow-up after two to three weeks. We include a follow-up assessment with every job.' },
      { question: 'Can they spread between apartments?', answer: 'Yes, German cockroaches travel along pipes and shared walls. If you live in a unit, treating adjacent units helps prevent reinfestation.' },
    ],
    schemaType: 'Service',
    serviceType: 'German cockroach extermination',
    areaServed: 'Sydney metropolitan area',
  },
  {
    slug: 'ant-control',
    name: 'Ant Control',
    title: 'Ant Control Sydney',
    metaTitle: 'Ant Control Sydney | Ant Nest Treatment & Prevention',
    metaDescription: 'Stop ants invading your home or business. Pest-Aside Sydney treats ant nests and trails with targeted, long-lasting solutions for all common Sydney ant species.',
    image: '/images/ants.jpg',
    heroHeadline: 'Ant control',
    heroSub: 'Trails stopped, nests found.',
    intro: 'Ants might seem small, but once they find a food source they arrive in numbers. Sydney homes deal with several species, from coastal brown ants to sugar ants and the invasive Argentine ant. Spraying the trail only kills the foragers you can see, the nest keeps producing replacements. Pest-Aside traces the colony, treats the nest directly, and uses targeted baits that worker ants carry back to the queen, stopping the problem at its source.',
    signs: [
      'Visible ant trails along walls, skirtings, window frames or paths',
      'Small piles of fine soil near paving, garden edges or skirtings',
      'Ants in the kitchen, pantry or around pet food',
      'Sawdust-like frass from carpenter ants in timber',
    ],
    treatment: [
      'Nest identification and direct treatment',
      'Targeted bait that workers carry back to the colony',
      'Perimeter treatment of entry points and trails',
      'Non-repellent barrier treatment where appropriate',
    ],
    prevention: [
      'Clean up spills and crumbs immediately and store food sealed',
      'Trim vegetation away from exterior walls',
      'Seal cracks in paving, paths and around window frames',
      'Reduce moisture from irrigation, leaks and drainage',
    ],
    faqs: [
      { question: 'Why do the ants keep coming back?', answer: 'Spraying a trail only kills foragers. The nest survives and sends out more. We use bait that workers carry back to the queen, eliminating the colony itself.' },
      { question: 'Are your ant treatments safe outdoors?', answer: 'Yes. We select products appropriate for the location and apply them to nests and entry points, not broadcast across lawns or gardens.' },
      { question: 'How quickly will I see results?', answer: 'Bait treatments can take a few days to work through the colony. You should see a clear reduction within the first week.' },
    ],
    schemaType: 'Service',
    serviceType: 'Ant nest treatment and prevention',
    areaServed: 'Sydney metropolitan area',
  },
  {
    slug: 'bed-bug-control',
    name: 'Bed Bug Control',
    title: 'Bed Bug Control Sydney',
    metaTitle: 'Bed Bug Control Sydney | Discreet Bed Bug Treatment',
    metaDescription: 'Bed bugs are stressful and stubborn. Pest-Aside Sydney provides discreet, thorough bed bug treatment for homes and hotels. Heat and chemical options available.',
    image: '/images/bed-bug.jpg',
    heroHeadline: 'Bed bug control',
    heroSub: 'Sleep easy again.',
    intro: 'Bed bugs are one of the most distressing pests a household can face. They hide in mattress seams, bed frames, skirtings and furniture, emerging at night to feed. They spread easily through travel, second-hand furniture and shared walls, and they are notoriously difficult to eliminate without professional help. Pest-Aside provides discreet, thorough treatment that targets bed bugs at every life stage, from eggs to adults, so you can sleep with confidence again.',
    signs: [
      'Itchy red bites, often in a line or cluster, on waking',
      'Small dark spots on sheets, mattresses or bed frames',
      'Rusty or reddish stains on bedding from crushed bugs',
      'Live bugs or shed skins in mattress seams and furniture joints',
    ],
    treatment: [
      'Thorough inspection of sleeping areas, furniture and adjoining rooms',
      'Targeted treatment of mattress seams, bed frames, skirtings and furniture',
      'Crack and crevice treatment of all harbourage points',
      'Follow-up treatment to eliminate newly hatched bugs',
    ],
    prevention: [
      'Inspect luggage and second-hand furniture before bringing it inside',
      'Use mattress encasements designed for bed bugs',
      'Keep bedrooms clutter-free to reduce hiding spots',
      'Be cautious with shared-laundry and high-turnover accommodation',
    ],
    faqs: [
      { question: 'Do I need to throw out my mattress?', answer: 'Not usually. We treat the mattress and frame directly. A bed-bug-proof encasement is recommended after treatment to trap any remaining bugs.' },
      { question: 'Why do I need more than one treatment?', answer: 'Bed bug eggs are resistant to most treatments. A second visit two to three weeks later catches any bugs that hatched after the first treatment.' },
      { question: 'How do bed bugs spread?', answer: 'They travel on luggage, clothing and second-hand furniture. They can also move between apartments and hotel rooms through shared walls.' },
    ],
    schemaType: 'Service',
    serviceType: 'Bed bug inspection and treatment',
    areaServed: 'Sydney metropolitan area',
  },
  {
    slug: 'mice-control',
    name: 'Mice Control',
    title: 'Mice Control Sydney',
    metaTitle: 'Mice Control Sydney | Mouse Removal & Proofing',
    metaDescription: 'Mice in your home or business? Pest-Aside Sydney provides mice removal, baiting and proofing to keep them out. Fast, family-safe and effective.',
    image: '/images/mice.jpg',
    heroHeadline: 'Mice control',
    heroSub: 'Small visitors, big relief.',
    intro: 'Mice are the most common rodent problem in Sydney homes. They squeeze through gaps as small as a pencil, breed rapidly, and contaminate food with droppings and urine. They also chew wiring, which creates a real fire risk. Pest-Aside combines strategic baiting with proofing, sealing the entry points mice use to get inside, so the problem does not return the moment treatment ends.',
    signs: [
      'Droppings like dark grains of rice in cupboards, under sinks or along walls',
      'Scratching or scurrying sounds in ceilings or walls at night',
      'Chewed food packaging, wiring or furniture',
      'Greasy rub marks along skirtings and entry points',
    ],
    treatment: [
      'Strategic baiting in tamper-resistant stations',
      'Trapping in active indoor areas for fast knockdown',
      'Proofing of entry points: gaps, vents, pipes and weep holes',
      'Follow-up to confirm activity has stopped',
    ],
    prevention: [
      'Seal gaps around pipes, vents and weep holes',
      'Store food in sealed glass or hard plastic containers',
      'Keep gardens trimmed and reduce hiding spots near walls',
      'Secure rubbish and compost bins',
    ],
    faqs: [
      { question: 'How do mice get into my home?', answer: 'Mice can squeeze through gaps as small as 6mm. We seal these entry points as part of the treatment so new mice cannot follow.' },
      { question: 'Is baiting safe with pets?', answer: 'We use tamper-resistant bait stations that keep bait away from children and pets. We will advise on placement for your specific situation.' },
      { question: 'How quickly will the mice be gone?', answer: 'Most activity stops within a week of treatment. Proofing ensures the problem does not recur.' },
    ],
    schemaType: 'Service',
    serviceType: 'Mice removal and proofing',
    areaServed: 'Sydney metropolitan area',
  },
  {
    slug: 'rat-control',
    name: 'Rat Control',
    title: 'Rat Control Sydney',
    metaTitle: 'Rat Control Sydney | Rat Removal, Baiting & Proofing',
    metaDescription: 'Rats in your roof, walls or yard? Pest-Aside Sydney provides professional rat baiting, trapping and proofing. Stop rats at the source and keep them out.',
    image: '/images/rat.jpg',
    heroHeadline: 'Rat control',
    heroSub: 'Tough problems, dealt with.',
    intro: 'Rats are more than a nuisance. They spread disease, contaminate food, damage insulation and wiring, and can cause significant structural damage. Sydney has both roof rats, which nest above ground, and Norway rats, which burrow. Pest-Aside identifies the species, locates the nest, and uses a combination of baiting, trapping and proofing to eliminate the colony and prevent re-entry.',
    signs: [
      'Loud scratching or thumping in the roof cavity at night',
      'Large droppings in the roof, under the house or near food sources',
      'Chewed wiring, insulation, pipes or timber',
      'Burrows or runs in the garden, under sheds or along fences',
    ],
    treatment: [
      'Inspection to identify the species and locate nests and runs',
      'Strategic baiting in secure, tamper-resistant stations',
      'Trapping in roof cavities and indoor areas',
      'Proofing of entry points to prevent re-entry',
    ],
    prevention: [
      'Trim trees and branches away from the roof',
      'Seal gaps in eaves, vents and around pipes',
      'Secure rubbish, compost and pet food',
      'Remove hiding spots: clear clutter, long grass and stored materials',
    ],
    faqs: [
      { question: 'What is the difference between rats and mice?', answer: 'Rats are larger, louder and cause more damage. Roof rats nest above ground in ceilings, while Norway rats burrow. Treatment and proofing differ accordingly.' },
      { question: 'Can rats really cause a fire?', answer: 'Yes. Rats chew electrical wiring, which is a documented cause of house fires. Prompt removal is important for safety, not just comfort.' },
      { question: 'How do you stop them coming back?', answer: 'We proof the entry points: gaps in eaves, vents, pipes and weep holes. Without proofing, baiting only solves the problem temporarily.' },
    ],
    schemaType: 'Service',
    serviceType: 'Rat removal and proofing',
    areaServed: 'Sydney metropolitan area',
  },
  {
    slug: 'wasp-control',
    name: 'Wasp Control',
    title: 'Wasp Control Sydney',
    metaTitle: 'Wasp Control Sydney | Wasp Nest Removal & Treatment',
    metaDescription: 'Wasp nest on your property? Pest-Aside Sydney safely removes and treats wasp nests. Fast response for paper wasps, mud wasps and European wasps across Sydney.',
    image: '/images/wasp.jpg',
    heroHeadline: 'Wasp control',
    heroSub: 'Nests gone, safely.',
    intro: 'Wasps are aggressive when threatened and can sting repeatedly, making them a real danger around homes, playgrounds and outdoor dining. Sydney deals with several species, including paper wasps, mud daubers and the European wasp, which is particularly aggressive and can nest in wall cavities or underground. Pest-Aside locates and treats nests safely, using the right approach for the species and nest location.',
    signs: [
      'Wasps flying in and out of a single point, especially in eaves, walls or garden',
      'Visible paper or mud nests under eaves, in bushes or on fences',
      'A buzzing sound from wall cavities or roof spaces',
      'Increased wasp activity around outdoor food, drinks or bins',
    ],
    treatment: [
      'Nest location and species identification',
      'Direct treatment of the nest at the appropriate time of day',
      'Removal of the treated nest where accessible',
      'Advice on reducing attractants around the property',
    ],
    prevention: [
      'Remove old nests in winter to prevent reuse',
      'Seal gaps in walls, eaves and roof spaces before spring',
      'Keep outdoor bins sealed and clean',
      'Avoid leaving sweet drinks and food uncovered outdoors',
    ],
    faqs: [
      { question: 'Can I remove a wasp nest myself?', answer: 'We strongly advise against it. Wasps can sting repeatedly and aggressively defend the nest. Professional treatment is faster, safer and more effective.' },
      { question: 'How fast can you respond?', answer: 'Wasp nests are treated as a priority. In most cases we can attend the same or next day, especially for aggressive species like the European wasp.' },
      { question: 'Do wasps return to the same spot?', answer: 'They can. Removing the old nest and sealing the entry point helps prevent a new nest in the same location.' },
    ],
    schemaType: 'Service',
    serviceType: 'Wasp nest removal and treatment',
    areaServed: 'Sydney metropolitan area',
  },
  {
    slug: 'silverfish-control',
    name: 'Silverfish Control',
    title: 'Silverfish Control Sydney',
    metaTitle: 'Silverfish Control Sydney | Silverfish Treatment & Prevention',
    metaDescription: 'Silverfish damaging books, clothes or paperwork? Pest-Aside Sydney provides targeted silverfish treatment and moisture control advice for lasting protection.',
    image: '/images/silverfish.webp',
    heroHeadline: 'Silverfish control',
    heroSub: 'Protect what matters.',
    intro: 'Silverfish are nocturnal, fast-moving insects that thrive in damp, dark environments. They feed on paper, books, photographs, clothing, wallpaper paste and even dried food. While they do not spread disease, they can cause real damage to irreplaceable items. Pest-Aside treats the areas silverfish hide and breed, and addresses the moisture conditions that allow them to thrive, for lasting protection of your home and belongings.',
    signs: [
      'Small silver, teardrop-shaped insects, 13 to 25mm, seen at night',
      'Yellow stains or small holes in books, paper or clothing',
      'Damage to wallpaper, photos or stored paperwork',
      'Sighting in damp areas: bathrooms, laundries, roof spaces and basements',
    ],
    treatment: [
      'Targeted treatment of cracks, crevices and harbourage areas',
      'Treatment of roof voids, subfloors and damp areas',
      'Application to bookshelves, wardrobes and storage areas',
      'Moisture control advice to remove the conditions silverfish need',
    ],
    prevention: [
      'Reduce humidity with ventilation or dehumidifiers',
      'Store books and paper in dry, sealed containers',
      'Fix leaks and improve drainage around the home',
      'Keep stored clothing clean and dry, off the floor',
    ],
    faqs: [
      { question: 'Are silverfish dangerous?', answer: 'No, they do not bite or spread disease. But they can damage books, photos, clothing and paperwork, which is often irreplaceable.' },
      { question: 'Why do I have silverfish?', answer: 'Silverfish need moisture. They are most common in damp areas like bathrooms, laundries and roof spaces. Reducing humidity is key to long-term control.' },
      { question: 'How do I protect my books and clothes?', answer: 'Store them in dry, sealed containers and treat the storage area. We can advise on the best approach for your situation.' },
    ],
    schemaType: 'Service',
    serviceType: 'Silverfish treatment and prevention',
    areaServed: 'Sydney metropolitan area',
  },
];

export const getServiceBySlug = (slug: string): ServiceData | undefined =>
  pestServices.find((s) => s.slug === slug);
